// Additional detailed roadmaps to replace old ones
// These can be merged into script.js

const detailedRoadmaps = {
    "Cyber Security": {
        summary: "Begin with networking and OS basics, then learn security tools, threats, and how defenders protect systems.",
        summaryHi: "Networking और OS से शुरू करो, फिर security tools, threats, और defense सीखो।",
        summaryHinglish: "Networking aur OS se shuro karo, fir security tools, threats, aur defense sikho.",
        roadmap: [
            { 
                title: "Phase 1: Networking & System Fundamentals 🌐",
                titleHi: "चरण 1: Networking और System की बुनियाद 🌐",
                titleHinglish: "Phase 1: Networking & System Fundamentals 🌐",
                goal: "Understand how systems connect and communicate",
                goalHi: "Understand कैसे systems connect होते हैं",
                goalHinglish: "Systems kaise connect hote hain ye samjho",
                items: ["Networking basics", "TCP/IP", "Ports", "Operating systems", "Linux basics"],
                language: ["Linux"],
                dsa: ["Network protocols", "Data structures"],
                oops: ["N/A"],
                database: ["N/A"],
                tools: ["Linux terminal", "Wireshark", "ifconfig"],
                projects: ["Set up a Linux VM", "Analyze network traffic"],
                languageHi: ["Linux"],
                dsaHi: ["Network protocols"],
                oopsHi: ["N/A"],
                databaseHi: ["N/A"],
                toolsHi: ["Linux", "Wireshark"],
                projectsHi: ["Linux VM setup करो", "Network traffic analyze करो"],
                languageHinglish: ["Linux"],
                dsaHinglish: ["Network protocols"],
                oopsHinglish: ["N/A"],
                databaseHinglish: ["N/A"],
                toolsHinglish: ["Linux", "Wireshark"],
                projectsHinglish: ["Linux VM setup karo", "Network traffic analyze karo"]
            },
            { 
                title: "Phase 2: Security Fundamentals 🔒",
                titleHi: "चरण 2: Security की बुनियाद 🔒",
                titleHinglish: "Phase 2: Security Fundamentals 🔒",
                goal: "Learn what threats and defense mean",
                goalHi: "Threats और defense क्या हैं समझो",
                goalHinglish: "Threats aur defense kya hain ye samjho",
                items: ["CIA triad", "Authentication", "Encryption", "Firewalls", "Risk management"],
                language: ["Linux/Bash"],
                dsa: ["Cryptographic algorithms"],
                oops: ["Security design patterns"],
                database: ["Secure data storage"],
                tools: ["OpenSSL", "Encryption tools"],
                projects: ["Learn encryption basics", "Set up a firewall"],
                languageHi: ["Linux/Bash"],
                dsaHi: ["Cryptographic algorithms"],
                oopsHi: ["Security patterns"],
                databaseHi: ["Secure storage"],
                toolsHi: ["OpenSSL", "Encryption"],
                projectsHi: ["Encryption सीखो", "Firewall setup करो"],
                languageHinglish: ["Linux/Bash"],
                dsaHinglish: ["Cryptographic algorithms"],
                oopsHinglish: ["Security patterns"],
                databaseHinglish: ["Secure storage"],
                toolsHinglish: ["OpenSSL", "Encryption"],
                projectsHinglish: ["Encryption seekho", "Firewall setup karo"]
            },
            { 
                title: "Phase 3: Defensive Security 🛡️",
                titleHi: "चरण 3: Defensive Security 🛡️",
                titleHinglish: "Phase 3: Defensive Security 🛡️",
                goal: "Protect systems and detect issues",
                goalHi: "Systems को protect करो और issues detect करो",
                goalHinglish: "Systems ko protect karo aur issues detect karo",
                items: ["Threat analysis", "Security logs", "Linux security", "Vulnerability scanning"],
                language: ["Linux/Python"],
                dsa: ["Log analysis patterns"],
                oops: ["Security architecture"],
                database: ["Security information management"],
                tools: ["Splunk", "ELK stack", "SIEM tools"],
                projects: ["Set up logging", "Analyze security events"],
                languageHi: ["Linux/Python"],
                dsaHi: ["Log patterns"],
                oopsHi: ["Security architecture"],
                databaseHi: ["SIEM"],
                toolsHi: ["Splunk", "ELK"],
                projectsHi: ["Logging setup करो", "Events analyze करो"],
                languageHinglish: ["Linux/Python"],
                dsaHinglish: ["Log patterns"],
                oopsHinglish: ["Security architecture"],
                databaseHinglish: ["SIEM"],
                toolsHinglish: ["Splunk", "ELK"],
                projectsHinglish: ["Logging setup karo", "Events analyze karo"]
            },
            { 
                title: "Phase 4: Ethical Hacking & Penetration Testing ⚔️",
                titleHi: "चरण 4: Ethical Hacking और Penetration Testing ⚔️",
                titleHinglish: "Phase 4: Ethical Hacking & Penetration Testing ⚔️",
                goal: "Practice ethical security testing safely",
                goalHi: "Ethical testing safely करो",
                goalHinglish: "Ethical testing safely karo",
                items: ["Reconnaissance", "Scanning", "Web vulnerabilities", "Exploitation techniques"],
                language: ["Linux/Bash/Python"],
                dsa: ["Exploitation algorithms"],
                oops: ["Offensive patterns"],
                database: ["Vulnerability databases"],
                tools: ["Metasploit", "Burp Suite", "Kali Linux"],
                projects: ["Perform a pentest", "Find vulnerabilities in lab"],
                languageHi: ["Linux/Bash/Python"],
                dsaHi: ["Exploitation algorithms"],
                oopsHi: ["Offensive patterns"],
                databaseHi: ["Vulnerability DB"],
                toolsHi: ["Metasploit", "Burp"],
                projectsHi: ["Pentest करो", "Vulnerabilities find करो"],
                languageHinglish: ["Linux/Bash/Python"],
                dsaHinglish: ["Exploitation algorithms"],
                oopsHinglish: ["Offensive patterns"],
                databaseHinglish: ["Vulnerability DB"],
                toolsHinglish: ["Metasploit", "Burp"],
                projectsHinglish: ["Pentest karo", "Vulnerabilities find karo"]
            },
            { 
                title: "Phase 5: Security Career Ready 💼",
                titleHi: "चरण 5: Security Career Ready 💼",
                titleHinglish: "Phase 5: Security Career Ready 💼",
                goal: "Prepare for real security work and certifications",
                goalHi: "Real security work और certifications के लिए तैयार हो",
                goalHinglish: "Real security work aur certifications ke liye ready ho",
                items: ["Security portfolio", "Certifications (CEH/OSCP)", "Career paths", "Interview prep"],
                language: ["Full security stack"],
                dsa: ["Advanced security algorithms"],
                oops: ["Enterprise security patterns"],
                database: ["Threat intelligence"],
                tools: ["SIEM platforms", "Threat intel tools"],
                projects: ["Build security lab", "Write security reports"],
                languageHi: ["Full security stack"],
                dsaHi: ["Advanced algorithms"],
                oopsHi: ["Enterprise patterns"],
                databaseHi: ["Threat intel"],
                toolsHi: ["SIEM", "Threat tools"],
                projectsHi: ["Security lab बनाओ", "Reports लिखो"],
                languageHinglish: ["Full security stack"],
                dsaHinglish: ["Advanced algorithms"],
                oopsHinglish: ["Enterprise patterns"],
                databaseHinglish: ["Threat intel"],
                toolsHinglish: ["SIEM", "Threat tools"],
                projectsHinglish: ["Security lab banao", "Reports likho"]
            }
        ],
        careers: ["Cyber Security Analyst", "Ethical Hacker", "SOC Analyst", "Penetration Tester", "Forensic Analyst", "Network Security Engineer"]
    }
};
